### ISSUE TITLE
Qs_Stamp

### ISSUE THREAD

**Issue by Snowlav** [DrunkSkipper/qs_stamp#1]
Hey, it's nice to see someone else trying to figure out instagram their implementation of the qs stamp.

I've been trying to convert this over into python since I currently only have it in JavaScript like they do on their web platform.

Would you be able to push me into a right direction on how to do so ?

**Comment by DrunkSkipper** [comment]
Hey.
This IS the signing algorithm, however, for obvious reasons, I've changed few things.
As for writing it on python, I didn't look at js version, this was reverse engineered from libquicksand.so of instagram 8.0 apk, which is IMHO easier than javascript.

**Comment by Snowlav** [comment]
could you elaborate on:

> for obvious reasons, I've changed few things.

Also the JS generation was not too complicated, but that's because I was able to extract it from their webpack as is (with a bit of stripping and cleaning up.. well a lot of it __sigh__)

Anyway, I think it's very cool to finally see someone else digging into this, would you be interested in combining powers to translate this algorithm to different languages?

Let me know! :smile: 
awesome work

**Comment by DrunkSkipper** [comment]
It's pretty straightforward rewriting this algo on mainstream languages like java or sharp.
What language are you interested in?

**Comment by Snowlav** [comment]
Python mainly and go would be interesting although I have little experience
in it, but mainly I'd like to rewrite it in python. Seeing python has a
sha256 module (hashlib) and numpy (for int64) I think it should for doable.
Your thoughts?

**Comment by DrunkSkipper** [comment]
It is. I' ll write it a bit later.

**Comment by mastak916** [comment]
So what does "however, for obvious reasons, I've changed few things" mean? Is it the same algo or not? 

The value your implementation returns doesn't match the one I get while sniffing android app v8.0.0

**Comment by Snowlav** [comment]
Oh damn you the man, let me know if you need the JavaScript implementation
or if you want me to run unit tests between the python and JS
implementations.
Op 30 jun. 2016 12:38 schreef "DrunkSkipper" notifications@github.com:

**Comment by DrunkSkipper** [comment]
@gaugger, as i said before, this IS instagram signing algo. However, I changed a few things in hash calculations, like entry barrier for script kiddies. Anyone who looked at other implementations will be able to fix it without any trouble.

**Comment by mastak916** [comment]
Could you drop me your email? I have a personal question for you.

**Comment by DrunkSkipper** [comment]
@gaugger just use my public email. I forgot to unhide it, but it's visible now.

**Comment by wnateg** [comment]
@Snowlav @DrunkSkipper Do you still have the JS implementation of the qs_stamp? Thanks.

**Comment by Snowlav** [comment]
Probably not, but it's been ditched anyway.
