### ISSUE TITLE
which parameters coming in input?

### ISSUE THREAD

**Issue by Radzhab** [DrunkSkipper/qs_stamp#2]
I see that program get six params

```
  unsigned int iterations 
  unsigned int size 
  int edgePercentage
  unsigned int shift
  std::string header{argv[5]};
```

Whats mean this?

**Comment by DrunkSkipper** [comment]
This are five params you get as challenge from serverside

**Comment by Snowlav** [comment]
If you are working with their web API you can extract these by making a simple un-authenticated GET request to `https://www.instagram.com/` .
To check manually you can use chrome dev tools console, and type in `window._sharedData.qs`
