### ISSUE TITLE
Incorrect generate stamp

### ISSUE THREAD

**Issue by Radzhab** [DrunkSkipper/qs_stamp#4]
I try use python code. In end of code i insert this

```
start = datetime.datetime.now()
print(generateStamp("7","42","100","10","EitgkNAguzU7feU8iQnRbsYptslgY04Q"))
print ("Finished in " + str(datetime.datetime.now()-start))
exit(0)
```

When i run app its infinitely return me 

```
0
1
1
1
...
```

**Comment by DrunkSkipper** [comment]
@Radzhab , I will investigate, although, it seems this algo is intended for shift values higher than 10

**Comment by DrunkSkipper** [comment]
As I thought, this is correct behavior. Use shift values > 10

**Comment by Radzhab** [comment]
i get from server shift = 10. If i change it to 11 it been work?
`"{"shift":10,"header":"6SPIRAAz8D7uaa7aeNblbXWdCQ5z21hH","edges":100,"blob":"AQC5APX0HWPsp_Q3e9sxIBgxNMrGc5OIHC9hgZ9WNBnsH5AzvGCy3tFuZJi9RFYG4SA75Wgrisx2tBhckWBm3yzgCsp3F-E6LITmnZ1yTasAmGUKBFUlSrMvHK0qvvysD0vUK0oFDcHiLtJ_4KRMw6m3U9oF2FzgYxbS1LTXIiTShoIfNQYTHCllnePHlNR_yWXLCnFaioZ-Yyijcxps_qc4my2Hxp5bg018E-3bQm5-7g","iterations":7,"size":42}"`

**Comment by DrunkSkipper** [comment]
@Radzhab, please post network trace in which you get this values

**Comment by Radzhab** [comment]
`print(generateStamp("10","42","100","18","j5lak2HXM9CID6yqP34rAUzpJsZeFW0g"))`

http://rgho.st/77yhxPnz5 url for fiddler requests.

**Comment by DrunkSkipper** [comment]
In your latter post shift = 18, which is correct, do you have a server response with your previous data, preferably as pcap?

**Comment by Radzhab** [comment]
sorry, i dont have pcap data. but i dont understand why algo not working with this data
("10","42","100","18","j5lak2HXM9CID6yqP34rAUzpJsZeFW0g")

**Comment by DrunkSkipper** [comment]
It works, but as I said before, to prevent people from abusing this algo on instagram, it has been changed a bit. So, no, you won't be able to use it unless you understand what you are doing.

**Comment by Radzhab** [comment]
i dont unserstand why you share project if it not working?)

**Comment by DrunkSkipper** [comment]
@Radzhab , so that those, who really need it can correct it for themselves.

**Comment by Radzhab** [comment]
who want find this key yet make it or buy it. Who can reverse yet reversed it.
