### ISSUE TITLE
Give us a hint

### ISSUE THREAD

**Issue by taggart-comet** [DrunkSkipper/qs_stamp#5]
Hello, thank you for awesome job! 
I'm trying to figure out the way to make code work properly. I have reversed libquicksand and trying to find where the catch is. Its actually not so simple (trust me I'm not a kid=) ). 
So could you give us a hint please?) 
I'm thinking this is in sipRound or QuickSandHeader, or maybe there is more than one trick.

**Comment by chanoc-b** [comment]
I would really appreciate it too =) I'm exactly in the same situation
Regardless of your decision,  you are G-R-E-A-T ! Thanks for sharing your work

**Comment by DrunkSkipper** [comment]
You really should look into constants used.

**Comment by taggart-comet** [comment]
Those constants, are they in one method or in few? I'm really exhausted of changing&trying =)

**Comment by taggart-comet** [comment]
I found 5 wrong constants in 2 functions and fixed them, and still got wrong result. Is your code work properly? Could you(@DrunkSkipper) give me first number of `'FnoLOM9sKWej2ZTDJV0tv8cyCfPXIAiB'`header?

**Comment by taggart-comet** [comment]
@chanoc-b, Have you succeeded? May we collaborate? my email is visible

**Comment by libalex** [comment]
@john-carter-from-virginia write me to alessandro56@yandex.ru
