### ISSUE TITLE
Incorrect qs

### ISSUE THREAD

**Issue by ghost** [DrunkSkipper/qs_stamp#6]
Hello
After I changed some constants, calculated qs only partly coincided with correct qs. What could be the problem?
I use MSVC 2015
Params: 10 42 100 18 KMIni9D6Q7f10xJHbRjgwsXFk8yr4aNo
Original & calculated QS: http://pastebin.com/jZPxFYmM

**Comment by ydaniels** [comment]
He said he intentionally changed some part of the code . which means you can try and figure it yourself or wait for another person to crack it open again of CU's sooner or later everything becomes public and people start to abuse it again.

**Comment by ghost** [comment]
I solved this problem, all generated correctly. Thank you!!!!!!

**Comment by Snowlav** [comment]
Seems like Instagram ditched the qs anyway :o

Op 28 jul. 2016 20:54 schreef "SergeyKush" notifications@github.com:
