### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Max0nyM** [DrunkSkipper/qs_stamp#8]
Can You Make it in C#?

**Comment by ghost** [comment]
Just make DDL from this code, it's simple

**Comment by Max0nyM** [comment]
from main.cpp?

**Comment by Max0nyM** [comment]
With DLL is OK. But why its very long time working ?
Finished in 0:08:43.990952

**Comment by DrunkSkipper** [comment]
Because there are tons of calculations. Only compiling languages are capable of fast enough performance. 
Also, @SergeyKush,  it's very nice of you supporting this code.
